/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Granite View Group: Demo
 * Environment: Production
 * Id: 8e2b3719-35c5-0076-37e5-0358199f9a11
 *
 * -------------------------------------------------------------------------------
 */

import type { LanguageCodenames } from "../system/languages.generated.ts";

/*
 * Type representing codename of 'f685268' language
 */
export type F685268LanguageCodename = keyof Pick<
	Record<LanguageCodenames, null>,
	"f685268"
>;

/*
 * Typeguard for codename of 'f685268' language
 */
export function isF685268LanguageCodename(
	value: string | undefined | null,
): value is F685268LanguageCodename {
	return (
		typeof value === "string" &&
		value === ("f685268" satisfies F685268LanguageCodename)
	);
}
