/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Kontent.ai Kickstart
 * Environment: Production
 * Id: 8e2b3719-35c5-0076-37e5-0358199f9a11
 *
 * -------------------------------------------------------------------------------
 */

export * from "./collections/default-collection.generated.ts";
export * from "./languages/default-project-language-language.generated.ts";
export * from "./system/collections.generated.ts";
export * from "./system/elements.generated.ts";
export * from "./system/languages.generated.ts";
export * from "./system/main.system.generated.ts";
export * from "./system/snippets.generated.ts";
export * from "./system/taxonomies.generated.ts";
export * from "./system/types.generated.ts";
export * from "./system/workflows.generated.ts";
export * from "./taxonomies/event-topic.generated.ts";
export * from "./taxonomies/event-type.generated.ts";
export * from "./types/article.generated.ts";
export * from "./types/event.generated.ts";
export * from "./types/landing-page.generated.ts";
export * from "./types/solution.generated.ts";
export * from "./types/video.generated.ts";
export * from "./workflows/default-workflow.generated.ts";
