/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Granite View Group: Demo
 * Environment: Production
 * Id: 8e2b3719-35c5-0076-37e5-0358199f9a11
 *
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.ts';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.ts';
import type { LanguageCodenames } from '../system/languages.generated.ts';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.ts';
           
            /*
* Type representing codename of 'Navigation Item' type
*/
            export type NavigationItemTypeCodename = keyof Pick<Record<TypeCodenames, null>, "navigation_item">;

            /*
* Typeguard for codename of 'Navigation Item' type
*/
            export function isNavigationItemTypeCodename(value: string | undefined | null): value is NavigationItemTypeCodename {
                return typeof value === 'string' && value === ('navigation_item' satisfies NavigationItemTypeCodename);
            }

/*
    * Navigation Item
    *
    * Id: 2f280b72-704f-5fe7-86a3-3170f1680426
* Codename: navigation_item
* External Id: navigation_item
    */
export type NavigationItemType = IContentItem<
{
/*
    * Title
    *
    * Codename: title
* Id: c3873be1-f65c-56cd-9b15-3a08a31a622e
* External Id: navigation_item_title_element
* Type: text
* Required: true
    */
                readonly title: Elements.TextElement;

/*
    * Slug
    *
    * Codename: slug
* Id: 892fb26b-0406-59b4-a39f-279823afc950
* External Id: navigation_item_slug_element
* Type: text
* Required: false
    */
                readonly slug: Elements.TextElement;

/*
    * Subpages
    *
    * Codename: subpages
* Id: 59505e1a-3320-5f84-a134-10e6f350aae1
* External Id: navigation_item_subpages_element
* Type: modular_content
* Required: false
* Allowed content types: navigation_item
    */
                readonly subpages: Elements.LinkedItemsElement<NavigationItemType>;}, 
NavigationItemTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Navigation Item
*/
export type NavigationItemTypeElementCodenames = 'title' | 'slug' | 'subpages';;

/*
    * Type guard for Navigation Item
    *
    * Id: 2f280b72-704f-5fe7-86a3-3170f1680426
* Codename: navigation_item
* External Id: navigation_item
    */
export function isNavigationItemType(item: IContentItem | undefined | null): item is NavigationItemType {
                return item?.system.type === ('navigation_item' satisfies NavigationItemTypeCodename);
            };



            