/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Granite View Group: Demo
 * Environment: Production
 * Id: 8e2b3719-35c5-0076-37e5-0358199f9a11
 *
 * -------------------------------------------------------------------------------
 */

import type { Elements, IContentItem } from "@kontent-ai/delivery-sdk";
import type { CollectionCodenames } from "../system/collections.generated.ts";
import type { LanguageCodenames } from "../system/languages.generated.ts";
import type { CoreType, TypeCodenames } from "../system/types.generated.ts";
import type {
	WorkflowCodenames,
	WorkflowStepCodenames,
} from "../system/workflows.generated.ts";

/*
 * Type representing codename of 'Page' type
 */
export type PageTypeCodename = keyof Pick<Record<TypeCodenames, null>, "page">;

/*
 * Typeguard for codename of 'Page' type
 */
export function isPageTypeCodename(
	value: string | undefined | null,
): value is PageTypeCodename {
	return (
		typeof value === "string" && value === ("page" satisfies PageTypeCodename)
	);
}

/*
 * Page
 *
 * Id: 5f02e921-31c7-5f5d-aba3-14d3b9b90dcb
 * Codename: page
 * External Id: page
 */
export type PageType = IContentItem<
	{
		/*
		 * Title
		 *
		 * Codename: title
		 * Id: 72ac755a-b8a1-5c25-8af7-7ef247f8571c
		 * External Id: page_title_element
		 * Type: text
		 * Required: true
		 */
		readonly title: Elements.TextElement;

		/*
		 * Slug
		 *
		 * Codename: slug
		 * Id: f87ab123-d357-5066-a438-b454c4177a0b
		 * External Id: page_slug_element
		 * Type: text
		 * Required: false
		 */
		readonly slug: Elements.TextElement;

		/*
		 * Body
		 *
		 * Codename: body
		 * Id: 281d0ea6-d3cf-5872-81f8-24c3e55d3c40
		 * External Id: page_body_element
		 * Type: rich_text
		 * Required: false
		 */
		readonly body: Elements.RichTextElement<CoreType>;
	},
	PageTypeCodename,
	LanguageCodenames,
	CollectionCodenames,
	WorkflowCodenames,
	WorkflowStepCodenames
>;

/*
 * Type representing all available element codenames for Page
 */
export type PageTypeElementCodenames = "title" | "slug" | "body";

/*
 * Type guard for Page
 *
 * Id: 5f02e921-31c7-5f5d-aba3-14d3b9b90dcb
 * Codename: page
 * External Id: page
 */
export function isPageType(
	item: IContentItem | undefined | null,
): item is PageType {
	return item?.system.type === ("page" satisfies PageTypeCodename);
}
