/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Granite View Group: Demo
 * Environment: Production
 * Id: 8e2b3719-35c5-0076-37e5-0358199f9a11
 *
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.ts';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.ts';
import type { ContentChannelTaxonomyTermCodenames, ContentChannelTaxonomyCodename } from '../taxonomies/content-channel.generated.ts';
import type { LanguageCodenames } from '../system/languages.generated.ts';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.ts';
           
            /*
* Type representing codename of 'Solution' type
*/
            export type SolutionTypeCodename = keyof Pick<Record<TypeCodenames, null>, "solution">;

            /*
* Typeguard for codename of 'Solution' type
*/
            export function isSolutionTypeCodename(value: string | undefined | null): value is SolutionTypeCodename {
                return typeof value === 'string' && value === ('solution' satisfies SolutionTypeCodename);
            }

/*
    * Solution
    *
    * Id: 38f94bc7-66ee-5c66-8402-15eb237d9835
* Codename: solution
* External Id: solution
    */
export type SolutionType = IContentItem<
{
/*
    * Headline
    *
    * Codename: headline
* Id: 9148131a-90f6-588a-bea4-c0397dbc554b
* External Id: solution_default_headline_element
* Type: text
* Required: true
    */
                readonly headline: Elements.TextElement;

/*
    * Introduction
    *
    * Codename: introduction
* Id: ec1fba9b-f3ed-5653-ac01-9815dca28b61
* External Id: solution_default_introduction_element
* Type: text
* Required: true
    */
                readonly introduction: Elements.TextElement;

/*
    * Image
    *
    * Codename: image
* Id: 481aa452-c113-5bb1-ae61-21b112bd0841
* External Id: solution_default_image_element
* Type: asset
* Required: true
    */
                readonly image: Elements.AssetsElement;

/*
    * Content Channel
    *
    * Codename: content_channel
* Id: 88732f76-1922-5714-ab79-81a5412938e8
* External Id: solution_content_channel_element
* Type: taxonomy
* Required: false
* Taxonomy: content_channel
    */
                readonly content_channel: Elements.TaxonomyElement<ContentChannelTaxonomyTermCodenames, ContentChannelTaxonomyCodename>;}, 
SolutionTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Solution
*/
export type SolutionTypeElementCodenames = 'headline' | 'introduction' | 'image' | 'content_channel';;

/*
    * Type guard for Solution
    *
    * Id: 38f94bc7-66ee-5c66-8402-15eb237d9835
* Codename: solution
* External Id: solution
    */
export function isSolutionType(item: IContentItem | undefined | null): item is SolutionType {
                return item?.system.type === ('solution' satisfies SolutionTypeCodename);
            };



            