/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Kontent.ai Kickstart
 * Environment: Production
 * Id: 8e2b3719-35c5-0076-37e5-0358199f9a11
 *
 * -------------------------------------------------------------------------------
 */


            import type { TypeCodenames } from '../system/types.generated.ts';
import type { Elements, IContentItem } from '@kontent-ai/delivery-sdk';
import type { CollectionCodenames } from '../system/collections.generated.ts';
import type { LanguageCodenames } from '../system/languages.generated.ts';
import type { WorkflowCodenames, WorkflowStepCodenames } from '../system/workflows.generated.ts';
           
            /*
* Type representing codename of 'Solution' type
*/
            export type SolutionTypeCodename = keyof Pick<Record<TypeCodenames, null>, "solution">;

            /*
* Typeguard for codename of 'Solution' type
*/
            export function isSolutionTypeCodename(value: string | undefined | null): value is SolutionTypeCodename {
                return typeof value === 'string' && value === ('solution' satisfies SolutionTypeCodename);
            }

/*
    * Solution
    *
    * Id: cfe09735-6b00-4b8a-b2f4-07b70603a82f
* Codename: solution
    */
export type SolutionType = IContentItem<
{
/*
    * Headline
    *
    * Codename: headline
* Id: 23bfd568-2e64-4bbb-8f0b-52d67396be5a
* Type: text
* Required: false
    */
                readonly headline: Elements.TextElement;

/*
    * Introduction
    *
    * Codename: introduction
* Id: 80921be4-e2b8-4dbf-bcb8-d54a61890fc2
* Type: text
* Required: false
    */
                readonly introduction: Elements.TextElement;

/*
    * Image
    *
    * Codename: image
* Id: 3e59d42a-3a57-49c4-8e57-51b323ac03c8
* Type: asset
* Required: false
    */
                readonly image: Elements.AssetsElement;}, 
SolutionTypeCodename, LanguageCodenames, CollectionCodenames, WorkflowCodenames, WorkflowStepCodenames>

/*
* Type representing all available element codenames for Solution
*/
export type SolutionTypeElementCodenames = 'headline' | 'introduction' | 'image';;

/*
    * Type guard for Solution
    *
    * Id: cfe09735-6b00-4b8a-b2f4-07b70603a82f
* Codename: solution
    */
export function isSolutionType(item: IContentItem | undefined | null): item is SolutionType {
                return item?.system.type === ('solution' satisfies SolutionTypeCodename);
            };



            