/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Kontent.ai Kickstart
 * Environment: Production
 * Id: 8e2b3719-35c5-0076-37e5-0358199f9a11
 *
 * -------------------------------------------------------------------------------
 */

import type { WorkflowCodenames } from "../system/workflows.generated.ts";

/*
 * Type representing codename of 'Default' workflow
 */
export type DefaultWorkflowCodename = keyof Pick<
	Record<WorkflowCodenames, null>,
	"default"
>;

/*
 * Typeguard for codename of 'Default' workflow
 */
export function isDefaultWorkflowCodename(
	value: string | undefined | null,
): value is DefaultWorkflowCodename {
	return (
		typeof value === "string" &&
		value === ("default" satisfies DefaultWorkflowCodename)
	);
}

/*
 * Array of all workflow step codenames
 */
export const defaultWorkflowStepCodenames = [
	"draft",
	"published",
	"archived",
	"scheduled",
] as const;

/*
 * Type representing all workflow step codenames
 */
export type DefaultWorkflowStepCodenames =
	(typeof defaultWorkflowStepCodenames)[number];

/*
 * Typeguard for workflow step codename
 */
export function isDefaultWorkflowStepCodename(
	value: string | undefined | null,
): value is DefaultWorkflowStepCodenames {
	return (
		typeof value === "string" &&
		(defaultWorkflowStepCodenames as readonly string[]).includes(value)
	);
}
