/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Granite View Group: Demo
 * Environment: Production
 * Id: 8e2b3719-35c5-0076-37e5-0358199f9a11
 *
 * -------------------------------------------------------------------------------
 */

import type { WorkflowCodenames } from "../system/workflows.generated.ts";

/*
 * Type representing codename of 'Regulated content' workflow
 */
export type RegulatedContentWorkflowCodename = keyof Pick<
	Record<WorkflowCodenames, null>,
	"regulated_content"
>;

/*
 * Typeguard for codename of 'Regulated content' workflow
 */
export function isRegulatedContentWorkflowCodename(
	value: string | undefined | null,
): value is RegulatedContentWorkflowCodename {
	return (
		typeof value === "string" &&
		value === ("regulated_content" satisfies RegulatedContentWorkflowCodename)
	);
}

/*
 * Array of all workflow step codenames
 */
export const regulatedContentWorkflowStepCodenames = [
	"regulated_draft",
	"legal_review",
	"published",
	"archived",
	"scheduled",
] as const;

/*
 * Type representing all workflow step codenames
 */
export type RegulatedContentWorkflowStepCodenames =
	(typeof regulatedContentWorkflowStepCodenames)[number];

/*
 * Typeguard for workflow step codename
 */
export function isRegulatedContentWorkflowStepCodename(
	value: string | undefined | null,
): value is RegulatedContentWorkflowStepCodenames {
	return (
		typeof value === "string" &&
		(regulatedContentWorkflowStepCodenames as readonly string[]).includes(value)
	);
}
