/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Kontent.ai Kickstart
 * Environment: Production
 * Id: 8e2b3719-35c5-0076-37e5-0358199f9a11
 *
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all collection codenames
 */
export const collectionCodenames = ["default"] as const;

/*
 * Type representing all collection codenames
 */
export type CollectionCodenames = (typeof collectionCodenames)[number];

/*
 * Typeguard for collection codename
 */
export function isCollectionCodename(
	value: string | undefined | null,
): value is CollectionCodenames {
	return (
		typeof value === "string" &&
		(collectionCodenames as readonly string[]).includes(value)
	);
}
