/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Granite View Group: Demo
 * Environment: Production
 * Id: 8e2b3719-35c5-0076-37e5-0358199f9a11
 *
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all element codenames
 */
export const elementCodenames = [
	"name",
	"image",
	"start_date",
	"end_date",
	"event_format",
	"market_topic",
	"description",
	"headline",
	"video_link",
	"caption",
	"autoplay",
	"subheadline",
	"hero_image",
	"body_copy",
	"featured_content",
	"title",
	"introduction",
	"publish_date",
	"content_channel",
	"effective_date",
	"version",
	"approved_by",
	"disclosure_id",
] as const;

/*
 * Type representing all element codenames
 */
export type ElementCodenames = (typeof elementCodenames)[number];

/*
 * Typeguard for element codename
 */
export function isElementCodename(
	value: string | undefined | null,
): value is ElementCodenames {
	return (
		typeof value === "string" &&
		(elementCodenames as readonly string[]).includes(value)
	);
}
