/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Kontent.ai Kickstart
 * Environment: Production
 * Id: 8e2b3719-35c5-0076-37e5-0358199f9a11
 *
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all language codenames
 */
export const languageCodenames = ["default"] as const;

/*
 * Type representing all language codenames
 */
export type LanguageCodenames = (typeof languageCodenames)[number];

/*
 * Typeguard for language codename
 */
export function isLanguageCodename(
	value: string | undefined | null,
): value is LanguageCodenames {
	return (
		typeof value === "string" &&
		(languageCodenames as readonly string[]).includes(value)
	);
}
