/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Kontent.ai Kickstart
 * Environment: Production
 * Id: 8e2b3719-35c5-0076-37e5-0358199f9a11
 *
 * -------------------------------------------------------------------------------
 */

import type { IDeliveryClient } from "@kontent-ai/delivery-sdk";
import type { CollectionCodenames } from "./collections.generated.ts";
import type { ElementCodenames } from "./elements.generated.ts";
import type { LanguageCodenames } from "./languages.generated.ts";
import type { TaxonomyCodenames } from "./taxonomies.generated.ts";
import type { CoreType, TypeCodenames } from "./types.generated.ts";
import type {
	WorkflowCodenames,
	WorkflowStepCodenames,
} from "./workflows.generated.ts";

/*
 * Core types for 'IDeliveryClient'
 */
export type CoreClientTypes = {
	readonly collectionCodenames: CollectionCodenames;
	readonly contentItemType: CoreType;
	readonly contentTypeCodenames: TypeCodenames;
	readonly elementCodenames: ElementCodenames;
	readonly languageCodenames: LanguageCodenames;
	readonly taxonomyCodenames: TaxonomyCodenames;
	readonly workflowCodenames: WorkflowCodenames;
	readonly workflowStepCodenames: WorkflowStepCodenames;
};

/*
 * Typed delivery client. Use this instead of 'IDeliveryClient'
 */
export type CoreDeliveryClient = IDeliveryClient<CoreClientTypes>;
