/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Granite View Group: Demo
 * Environment: Production
 * Id: 8e2b3719-35c5-0076-37e5-0358199f9a11
 *
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all snippet codenames
 */
export const snippetCodenames = [] as const;

/*
 * Type representing all snippet codenames
 */
export type SnippetCodenames = (typeof snippetCodenames)[number];

/*
 * Typeguard for snippet codename
 */
export function isSnippetCodename(
	value: string | undefined | null,
): value is SnippetCodenames {
	return (
		typeof value === "string" &&
		(snippetCodenames as readonly string[]).includes(value)
	);
}
