/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Granite View Group: Demo
 * Environment: Production
 * Id: 8e2b3719-35c5-0076-37e5-0358199f9a11
 *
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all taxonomy codenames
 */
export const taxonomyCodenames = [
	"event_format",
	"market_topic",
	"content_channel",
] as const;

/*
 * Type representing all taxonomy codenames
 */
export type TaxonomyCodenames = (typeof taxonomyCodenames)[number];

/*
 * Typeguard for taxonomy codename
 */
export function isTaxonomyCodename(
	value: string | undefined | null,
): value is TaxonomyCodenames {
	return (
		typeof value === "string" &&
		(taxonomyCodenames as readonly string[]).includes(value)
	);
}
