/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Granite View Group: Demo
 * Environment: Production
 * Id: 8e2b3719-35c5-0076-37e5-0358199f9a11
 *
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all workflow codenames
 */
export const workflowCodenames = ["default", "regulated_content"] as const;

/*
 * Type representing all workflow codenames
 */
export type WorkflowCodenames = (typeof workflowCodenames)[number];

/*
 * Typeguard for workflow codename
 */
export function isWorkflowCodename(
	value: string | undefined | null,
): value is WorkflowCodenames {
	return (
		typeof value === "string" &&
		(workflowCodenames as readonly string[]).includes(value)
	);
}

/*
 * Array of all workflow codenames
 */
export const workflowStepCodenames = [
	"draft",
	"published",
	"archived",
	"scheduled",
	"regulated_draft",
	"legal_review",
] as const;

/*
 * Type representing all workflow codenames
 */
export type WorkflowStepCodenames = (typeof workflowStepCodenames)[number];

/*
 * Typeguard for workflow codename
 */
export function isWorkflowStepCodename(
	value: string | undefined | null,
): value is WorkflowStepCodenames {
	return (
		typeof value === "string" &&
		(workflowStepCodenames as readonly string[]).includes(value)
	);
}
