/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Granite View Group: Demo
 * Environment: Production
 * Id: 8e2b3719-35c5-0076-37e5-0358199f9a11
 *
 * -------------------------------------------------------------------------------
 */

import type { TaxonomyCodenames } from "../system/taxonomies.generated.ts";

/*
 * Type representing codename of 'Content Channel' taxonomy
 */
export type ContentChannelTaxonomyCodename = keyof Pick<
	Record<TaxonomyCodenames, null>,
	"content_channel"
>;

/*
 * Typeguard for codename of 'Content Channel' taxonomy
 */
export function isContentChannelTaxonomyCodename(
	value: string | undefined | null,
): value is ContentChannelTaxonomyCodename {
	return (
		typeof value === "string" &&
		value === ("content_channel" satisfies ContentChannelTaxonomyCodename)
	);
}

/*
 * Array of all taxonomy term codenames
 */
export const contentChannelTaxonomyTermCodenames = [
	"public_web",
	"intranet",
	"knowledge_base",
	"regulated_docs",
] as const;

/*
 * Type representing all taxonomy term codenames
 */
export type ContentChannelTaxonomyTermCodenames =
	(typeof contentChannelTaxonomyTermCodenames)[number];

/*
 * Typeguard for taxonomy term codename
 */
export function isContentChannelTaxonomyTermCodename(
	value: string | undefined | null,
): value is ContentChannelTaxonomyTermCodenames {
	return (
		typeof value === "string" &&
		(contentChannelTaxonomyTermCodenames as readonly string[]).includes(value)
	);
}
