/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Granite View Group: Demo
 * Environment: Production
 * Id: 8e2b3719-35c5-0076-37e5-0358199f9a11
 *
 * -------------------------------------------------------------------------------
 */

import type { TaxonomyCodenames } from "../system/taxonomies.generated.ts";

/*
 * Type representing codename of 'Event Format' taxonomy
 */
export type EventFormatTaxonomyCodename = keyof Pick<
	Record<TaxonomyCodenames, null>,
	"event_format"
>;

/*
 * Typeguard for codename of 'Event Format' taxonomy
 */
export function isEventFormatTaxonomyCodename(
	value: string | undefined | null,
): value is EventFormatTaxonomyCodename {
	return (
		typeof value === "string" &&
		value === ("event_format" satisfies EventFormatTaxonomyCodename)
	);
}

/*
 * Array of all taxonomy term codenames
 */
export const eventFormatTaxonomyTermCodenames = [
	"briefing",
	"webinar",
	"roundtable",
] as const;

/*
 * Type representing all taxonomy term codenames
 */
export type EventFormatTaxonomyTermCodenames =
	(typeof eventFormatTaxonomyTermCodenames)[number];

/*
 * Typeguard for taxonomy term codename
 */
export function isEventFormatTaxonomyTermCodename(
	value: string | undefined | null,
): value is EventFormatTaxonomyTermCodenames {
	return (
		typeof value === "string" &&
		(eventFormatTaxonomyTermCodenames as readonly string[]).includes(value)
	);
}
