/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Granite View Group: Demo
 * Environment: Production
 * Id: 8e2b3719-35c5-0076-37e5-0358199f9a11
 *
 * -------------------------------------------------------------------------------
 */

import type { TaxonomyCodenames } from "../system/taxonomies.generated.ts";

/*
 * Type representing codename of 'Market Topic' taxonomy
 */
export type MarketTopicTaxonomyCodename = keyof Pick<
	Record<TaxonomyCodenames, null>,
	"market_topic"
>;

/*
 * Typeguard for codename of 'Market Topic' taxonomy
 */
export function isMarketTopicTaxonomyCodename(
	value: string | undefined | null,
): value is MarketTopicTaxonomyCodename {
	return (
		typeof value === "string" &&
		value === ("market_topic" satisfies MarketTopicTaxonomyCodename)
	);
}

/*
 * Array of all taxonomy term codenames
 */
export const marketTopicTaxonomyTermCodenames = [
	"markets_trading",
	"risk_management",
	"regulation_compliance",
	"payments",
] as const;

/*
 * Type representing all taxonomy term codenames
 */
export type MarketTopicTaxonomyTermCodenames =
	(typeof marketTopicTaxonomyTermCodenames)[number];

/*
 * Typeguard for taxonomy term codename
 */
export function isMarketTopicTaxonomyTermCodename(
	value: string | undefined | null,
): value is MarketTopicTaxonomyTermCodenames {
	return (
		typeof value === "string" &&
		(marketTopicTaxonomyTermCodenames as readonly string[]).includes(value)
	);
}
