/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Granite View Group: Demo
 * Environment: Production
 * Id: 8e2b3719-35c5-0076-37e5-0358199f9a11
 *
 * -------------------------------------------------------------------------------
 */

import type { CollectionCodenames } from "../system/collections.generated.ts";

/*
 * Type representing codename of 'Knowledge Base' collection
 */
export type KnowledgeBaseCollectionCodename = keyof Pick<
	Record<CollectionCodenames, null>,
	"knowledge_base"
>;

/*
 * Typeguard for codename of 'Knowledge Base' collection
 */
export function isKnowledgeBaseCollectionCodename(
	value: string | undefined | null,
): value is KnowledgeBaseCollectionCodename {
	return (
		typeof value === "string" &&
		value === ("knowledge_base" satisfies KnowledgeBaseCollectionCodename)
	);
}
