/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Granite View Group: Demo
 * Environment: Production
 * Id: 8e2b3719-35c5-0076-37e5-0358199f9a11
 *
 * -------------------------------------------------------------------------------
 */

import type { CollectionCodenames } from "../system/collections.generated.ts";

/*
 * Type representing codename of 'Public Web' collection
 */
export type PublicWebCollectionCodename = keyof Pick<
	Record<CollectionCodenames, null>,
	"public_web"
>;

/*
 * Typeguard for codename of 'Public Web' collection
 */
export function isPublicWebCollectionCodename(
	value: string | undefined | null,
): value is PublicWebCollectionCodename {
	return (
		typeof value === "string" &&
		value === ("public_web" satisfies PublicWebCollectionCodename)
	);
}
