/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@10.0.1'.
 *
 * (c) Kontent.ai
 *
 * -------------------------------------------------------------------------------
 *
 * Project: Granite View Group: Demo
 * Environment: Production
 * Id: 8e2b3719-35c5-0076-37e5-0358199f9a11
 *
 * -------------------------------------------------------------------------------
 */

import type { CollectionCodenames } from "../system/collections.generated.ts";

/*
 * Type representing codename of 'Regulated Docs' collection
 */
export type RegulatedDocsCollectionCodename = keyof Pick<
	Record<CollectionCodenames, null>,
	"regulated_docs"
>;

/*
 * Typeguard for codename of 'Regulated Docs' collection
 */
export function isRegulatedDocsCollectionCodename(
	value: string | undefined | null,
): value is RegulatedDocsCollectionCodename {
	return (
		typeof value === "string" &&
		value === ("regulated_docs" satisfies RegulatedDocsCollectionCodename)
	);
}
